name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: generate-snake
        uses: Platane/snk@v3
        with:
          github_user_name: bcmmarra
          outputs: dist/github-snake.svg
